#!/bin/bash

# Function to check for updates and install Python dependencies
check_for_updates_and_dependencies() {
    # Ask user if they want to check for updates
    read -p "Do you want to check for updates? (yes/no): " choice

    case "$choice" in
        [Yy][Ee][Ss]|[Yy])
            # Run git pull
            git fetch
            git reset --hard HEAD
            git merge --ff-only origin/$(git rev-parse --abbrev-ref HEAD)
            chmod +x csirt

            # Run pip update
            pip3 install --upgrade pip

            # Install or update Python dependencies
            if [ -f "requirements.txt" ]; then
                pip3 install --upgrade -r requirements.txt
            else
                echo "requirements.txt file not found. Skipping dependency installation/update."
            fi
            ;;
        [Nn][Oo]|[Nn])
            ;;
        *)
            echo "Invalid choice. Exiting."
            exit 1
            ;;
    esac
}

# Main script
check_for_updates_and_dependencies

# Ensure that laundry.py is executed from the script's directory
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
python3 "$DIR/laundry.py" "$@"
